---
- name: assert that platform is supported
  assert:
    that: ansible_distribution | lower in ["centos", "fedora"]
    message: "Unsupported platform ('{{ ansible_distribution }}')"

- name: assert that action is supported
  assert:
    that: copr_repository_action | lower in ["install", "remove"]
    message: "Unsupported action ('{{ copr_repository_action }}')"


- include_tasks: "{{ ansible_distribution | lower }}/{{ copr_repository_action | lower }}.yml"
  tags:
    - copr-repository
